# Generated by Django 2.2.4 on 2020-03-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_contact_and_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('stars', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=None, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='stars',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
